## spring-boot-dubbo-provider配置 ## 
spring: 
  dubbo: 

    application:  ## 应用配置参数 ##
      name: spring-boot-dubbo-provider     # 必填 服务治理 当前应用名称，用于注册中心计算应用间依赖关系，注意：消费者和提供者应用名不要一样，此参数不是匹配条件，你当前项目叫什么名字就填什么，和提供者消费者角色无关，比如：kylin应用调用了morgan应用的服务，则kylin项目配成kylin，morgan项目配成morgan，可能kylin也提供其它服务给别人使用，但kylin项目永远配成kylin，这样注册中心将显示kylin依赖于morgan 1.0.16以上版本

    base-package: com.spring.boot ## 提供者service和消费者所在的java包,多个包用逗号分割。服务扫描的包（使用注解时必须配置）

    registry: ## 注册中心支持的配置参数 ##
      protocol: zookeeper
      address: 127.0.0.1
      port: 2181

    protocol: ## 服务调用支持的类型 ##
      name: dubbo # 协议名称
      port: 20880 # 服务暴露端口

    provider: ## 提供者默认的配置参数 ##
      retries: 0  # 服务调用重试次数，服务发布者不给重试，让服务调用者自己重试，快速失败，用于性能调优
